---
- globalid: EBAY-US
  id: 0
  name: US

- globalid: EBAY-RU
  id: 215
  name: Russia

- globalid: EBAY-AT
  id: 16
  name: Austria

- globalid: EBAY-AU
  id: 15
  name: Australia

- globalid: EBAY-CH
  id: 193
  name: Switzerland

- globalid: EBAY-DE
  id: 77
  name: Germany

- globalid: EBAY-ENCA
  id: 2
  name: Canada

- globalid: EBAY-ES
  id: 186
  name: Spain

- globalid: EBAY-FR
  id: 71
  name: France

- globalid: EBAY-FRBE
  id: 23
  name: Belgium_French

- globalid: EBAY-FRCA
  id: 210
  name: CanadaFrench

- globalid: EBAY-GB
  id: 3
  name: UK

- globalid: EBAY-HK
  id: 201
  name: HongKong

- globalid: EBAY-IE
  id: 205
  name: Ireland

- globalid: EBAY-IN
  id: 203
  name: India

- globalid: EBAY-IT
  id: 101
  name: Italy

- globalid: EBAY-MOTOR
  id: 100

- globalid: EBAY-MY
  id: 207
  name: Malaysia

- globalid: EBAY-NL
  id: 146
  name: Netherlands

- globalid: EBAY-NLBE
  id: 123
  name: Belgium_Dutch

- globalid: EBAY-PH
  id: 211
  name: Philippines

- globalid: EBAY-PL
  id: 212
  name: Poland

- globalid: EBAY-SG
  id: 216
  name: Singapore
