---
- globalid: EBAY-US
  id: 0
  name: US
  currency: USD
  language: en
  domain: ebay.com

- globalid: EBAY-RU
  id: 215
  name: Russia
  currency: RUB
  language: ru
  domain: ebay.ru

- globalid: EBAY-AT
  id: 16
  name: Austria
  currency: EUR
  language: de
  domain: ebay.at

- globalid: EBAY-AU
  id: 15
  name: Australia
  currency: AUD
  language: en
  domain: ebay.com.au

- globalid: EBAY-CH
  id: 193
  name: Switzerland
  currency: CHF
  language: de
  domain: ebay.ch

- globalid: EBAY-DE
  id: 77
  name: Germany
  currency: EUR
  language: de
  domain: ebay.de

- globalid: EBAY-ENCA
  id: 2
  name: Canada
  currency: CAD
  language: en
  domain: ebay.ca

- globalid: EBAY-ES
  id: 186
  name: Spain
  currency: EUR
  language: es
  domain: ebay.es

- globalid: EBAY-FR
  id: 71
  name: France
  currency: EUR
  language: fr
  domain: ebay.fr

- globalid: EBAY-FRBE
  id: 23
  name: Belgium_French
  currency: EUR
  language: fr
  domain: ebay.be

- globalid: EBAY-FRCA
  id: 210
  name: CanadaFrench
  currency: CAD
  language: fr
  domain: ebay.ca

- globalid: EBAY-GB
  id: 3
  name: UK
  currency: GBP
  language: en
  domain: ebay.co.uk

- globalid: EBAY-HK
  id: 201
  name: HongKong
  currency: HKD
  language: zh
  domain: ebay.com.hk

- globalid: EBAY-IE
  id: 205
  name: Ireland
  currency: EUR
  language: en
  domain: ebay.ie

- globalid: EBAY-IN
  id: 203
  name: India
  currency: INR
  language: en
  domain: ebay.in

- globalid: EBAY-IT
  id: 101
  name: Italy
  currency: EUR
  language: it
  domain: ebay.it

- globalid: EBAY-MOTOR
  id: 100

- globalid: EBAY-MY
  id: 207
  name: Malaysia
  currency: MYR
  language: en
  domain: ebay.com.my

- globalid: EBAY-NL
  id: 146
  name: Netherlands
  currency: EUR
  language: nl
  domain: ebay.nl

- globalid: EBAY-NLBE
  id: 123
  name: Belgium_Dutch
  currency: EUR
  language: de
  domain: ebay.nl

- globalid: EBAY-PH
  id: 211
  name: Philippines
  currency: PHP
  language: en
  domain: ebay.ph

- globalid: EBAY-PL
  id: 212
  name: Poland
  currency: PLN
  language: pl
  domain: ebay.pl

- globalid: EBAY-SG
  id: 216
  name: Singapore
  currency: SGD
  language: en
  domain: ebay.com.sg
